IMAGE_HIEGHT  = 128
IMAGE_WIDTH   =  128
IMAGE_CHANNEL = 3

WIDTH_OUT = 128
HIEGHT_OUT = 128
CHANNEL_OUT = 1

DATASET_PATH  = data/
DATASET_TYPE  = citypair #citypair,semantic

EPOCHS = 10
SEED = 18
DEVICE = 0  ## cpu or 0,1,2
BATCH_SIZE = 4
LEARNING_RATE = 0.002

FLIPH = True
FLIPV = True
NORMALIZE = True
ROTATE = [0,45] # RANDOM ROTATION
NOISE = 0.012
BLUR  = True